version: '3'

# link https://github.com/emalherbi-zz/docker/blob/main/php8/Dockerfile

services:
  bdd:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin@44
      MYSQL_DATABASE: enisortir
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      #- ./mysql:/var/lib/mysql
      - db-data:/var/lib/mysql
    restart: always
    #command: --default-authentication-plugin=mysql_native_password

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - bdd

volumes:
  db-data:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###